fontsizemean = 20;
set(0,'DefaultLineLineWidth',3)
set(0,'DefaultAxesFontSize',fontsizemean)
set(0,'DefaultLineMarkerSize',14)
set(0,'DefaultAxesFontWeight','bold')
set(gca,'FontSize',fontsizemean)
set(get(gca,'Xlabel'),'FontSize',fontsizemean)
set(get(gca,'Ylabel'),'FontSize',fontsizemean)
set(get(gca,'Title'),'FontSize',fontsizemean)
set(get(gca,'Xlabel'),'FontWeight','bold')
set(get(gca,'Ylabel'),'FontWeight','bold')
set(get(gca,'Title'),'FontWeight','bold')